data/zilliqa/assets/zil1a5wkhunysdp9x0nww5qe6m2m8x2m3ygdpuu257/meta.json

RedC metadata updated

---

data/zilliqa/assets/zil1hau7z6rjltvjc95pphwj57umdpvv0d6kh2t8zk/meta.json

Added some more information for CARBON token. Thanks

updated basic info of CARBON Token

---

data/zilliqa/assets/zil14jmjrkvfcz2uvj3y69kl6gas34ecuf2j5ggmye/meta.json

Product and Linkedin added for REDC

---

data/zilliqa/assets/zil168qdlq4xsua6ac9hugzntqyasf8gs7aund882v/meta.json

Fixed SRV pull request issue, added whitepaper url

---

data/zilliqa/assets/zil1hau7z6rjltvjc95pphwj57umdpvv0d6kh2t8zk/meta.json

Should be all good now. Sorry about previous. However, did leave holders in as we meet the conditions for having it, and it lends 10 to the score. :)

Updated CARB Info

---

data/zilliqa/assets/zil1c6akv8k6dqaac7ft8ezk5gr2jtxrewfw8hc27d/meta.json

- [x ] PR doesn't have any merge conflict

Add DUCK whitepaper link

---

README.md
data/zilliqa/assets/zil1gtx89hjfagnhuhhfmr947p2g865r4dq0fmaxkt/meta.json
data/zilliqa/assets/zil1wh5z48kzn36jur7ffctcm09hl8e8jcypkpjzhe/meta.json

Donation fields

---

data/zilliqa/assets/zil1w5hwupgc9rxyuyd742g2c9annwahugrx80fw9h/meta.json

- [y ] PR doesn't have any merge conflict
- [na ] In case you are migrating a token, delete the old folder in the same PR

add more info for GARY

---

data/arweave/assets/usjm4PCxUd5mtaon7zc97-dt-3qf67yPyqgzLnLqk5A/logo-white.svg
data/arweave/assets/usjm4PCxUd5mtaon7zc97-dt-3qf67yPyqgzLnLqk5A/logo.svg

chore: update Verto logos

---

data/zilliqa/assets/zil1h63h5rlg7avatnlzhfnfzwn8vfspwkapzdy2aw/logo.svg
data/zilliqa/assets/zil1h63h5rlg7avatnlzhfnfzwn8vfspwkapzdy2aw/meta.json

Add XCAD Token on Zilliqa

---

data/zilliqa/assets/zil1qzwxvp3wz3q5ewzg3afesut9pqfax0sjdyna42/meta.json

Added our LinkedIn page.
Added our website address.
Added our Twitter handle.
Added our Contact Email.

Update MESSI info

---

data/zilliqa/assets/zil1jnv6d4mcnpvlsrzv42ygry8z2a5tlcrdls92gd/meta.json
logo.svg

[zilliqa] Add The One (ONE)

---

data/zilliqa/assets/zil1qzwxvp3wz3q5ewzg3afesut9pqfax0sjdyna42/meta.json

We added the whitepaper in the following Google Drive folder = https://drive.google.com/drive/folders/1vLwavgDen4X_CFHpOVkn1MKtnVWNG6N_
And in our site: https://messitokens.me

[zilliqa] Update Messi (MESSI)

---

data/zilliqa/assets/zil14d6wwelssqumu6w9c6kaucz2r57z34cxuh96lf/meta.json

[zilliqa] Update Shards (SHARDS)

---

data/zilliqa/assets/zil1w5hwupgc9rxyuyd742g2c9annwahugrx80fw9h/meta.json

Update GARY Metadata
Add Facebook, publicteam, linkedin, github
- [y ] Make sure to rebase or clean your history
- [y ] PR doesn't have any merge conflict
- [na ] In case you are migrating a token, delete the old folder in the same PR

[zilliqa] Update GaryToken (GARY)

---

data/zilliqa/assets/zil1pqcev4ykxla0jhy3anx32lnqgv8xncd8q57ql2/meta.json

Trying to update metadata. Please let me know of any issues.

[zilliqa] Update Sparda Wallet (SPW)

---

data/zilliqa/assets/zil12drvflckms6874ffuujcdxj75raavl4yfn4ssc/meta.json

[zilliqa] Update (RECAP)

---

data/zilliqa/assets/zil1ykcdhtgyercmv7ndfxt00wm9xzpq4k7hjmfm4e/meta.json
data/zilliqa/assets/zil1z4hxwnqk9gu6tamcw4umxss9wjpmrkhzdh4n85/meta.json

[zilliqa] Update Mambo (MAMBO) and Chocolate Stablecoin (FRANC)

---

data/zilliqa/assets/zil108ex3na3dvwnjq5p4nls4z3gjy8fx66693hf4d/meta.json

Update Consult Coin (CONSULT)

---

data/zilliqa/assets/zil1vdc79fg75sth96xnt6xmq5f55swcd5t6m5zhvn/meta.json

- [y ] Make sure to rebase or clean your history
- [y ] PR doesn't have any merge conflict
- [n/a ] In case you are migrating a token, delete the old folder in the same PR

[zilliqa] Update Yoda (Yoda)

---

data/zilliqa/assets/zil1l0g8u6f9g0fsvjuu74ctyla2hltefrdyt7k5f4/meta.json

**PLEASE READ AND DELETE THE CAPITALIZED TEXT, THE TITLE SECTION
AND THE SECTION THAT DOESN'T APPLY BEFORE SUBMITTING.**
DO NOT CLOSE AND REOPEN NEW PRS, UPDATE THE FIRST ONE YOU MADE.
READ CAREFULLY ALL THE FOLLOWING POINTS TO MAKE SURE YOUR PR
ADHERES TO THE STANDARD TO AVOID UNNECESSARY BACK AND FORTH.
**FAILURE TO READ BASIC INSTRUCTIONS WILL EVENTUALLY GET YOU
BLOCKED FROM THE REPO.**

updated ZLP token

---

data/zilliqa/assets/zil1jy3g5j9w5njqwxuuv3zwkz9syyueelmu7g080v/meta.json

[zilliqa] Update Unifee

---

data/zilliqa/assets/zil1ky37vhhdfuupqu0f40h7gqvfltw4u5f2hn4r0n/logo.svg
data/zilliqa/assets/zil1ky37vhhdfuupqu0f40h7gqvfltw4u5f2hn4r0n/meta.json

[zilliqa] Add Athlete Token (ATHLETE)

---

data/zilliqa/assets/zil1yk93f957fanapf0yszgm84p62xrxxfytj4d2tl/logo.svg
data/zilliqa/assets/zil1yk93f957fanapf0yszgm84p62xrxxfytj4d2tl/meta.json

[Zilliqa] Add Switcheo (SWTH)

---

data/zilliqa/assets/zil1g42zl93x8cc9numpkxc0g0vyde485rt8k3shkd/meta.json

( Zilliqa) Add Gaymer Blog Link (GAYMER)

Add Gaymer blog link

---

data/zilliqa/assets/zil1g42zl93x8cc9numpkxc0g0vyde485rt8k3shkd/meta.json

( Zilliqa ) Add GITHUB ( GAYMER )

( Zilliqa )  Update Add Github (GAYMER) 

---

data/arweave/ecosystem/decentland/meta.json

Update decentland (DLT)

---

data/arweave/ecosystem/arweavenews/meta.json

Update ArweaveNews (ARN)

---

data/zilliqa/assets/zil1hau7z6rjltvjc95pphwj57umdpvv0d6kh2t8zk/meta.json

CARB now has full utility use as the token pair and payment token for fees on CarbSwap (www.carbswap.app)

[zilliqa] Update Carbon (CARB)

---

data/zilliqa/assets/zil1p5suryq6q647usxczale29cu3336hhp376c627/meta.json

**PLEASE READ AND DELETE THE CAPITALIZED TEXT, THE TITLE SECTION
AND THE SECTION THAT DOESN'T APPLY BEFORE SUBMITTING.**
DO NOT CLOSE AND REOPEN NEW PRS, UPDATE THE FIRST ONE YOU MADE.
READ CAREFULLY ALL THE FOLLOWING POINTS TO MAKE SURE YOUR PR
ADHERES TO THE STANDARD TO AVOID UNNECESSARY BACK AND FORTH.
**FAILURE TO READ BASIC INSTRUCTIONS WILL EVENTUALLY GET YOU
BLOCKED FROM THE REPO.**

Update ZWAP metadata

---

data/zilliqa/assets/zil1m3m5jqqcaemtefnlk795qpw59daukra8prc43e/meta.json

**PLEASE READ AND DELETE THE CAPITALIZED TEXT, THE TITLE SECTION
AND THE SECTION THAT DOESN'T APPLY BEFORE SUBMITTING.**
DO NOT CLOSE AND REOPEN NEW PRS, UPDATE THE FIRST ONE YOU MADE.
READ CAREFULLY ALL THE FOLLOWING POINTS TO MAKE SURE YOUR PR
ADHERES TO THE STANDARD TO AVOID UNNECESSARY BACK AND FORTH.
**FAILURE TO READ BASIC INSTRUCTIONS WILL EVENTUALLY GET YOU
BLOCKED FROM THE REPO.**

Update HUNY metadata

---

data/thundercore/assets/0x218c3c3d49d0e7b37aff0d8bb079de36ae61a4c0/logo.svg
data/thundercore/assets/0x218c3c3d49d0e7b37aff0d8bb079de36ae61a4c0/meta.json
data/thundercore/ecosystem/nftmall/logo.svg
data/thundercore/ecosystem/nftmall/meta.json

[ThunderCore] Add NFTmall GEM Token (GEM)

---

data/thundercore/ecosystem/ttwof/meta.json

[ThunderCore] Update TTwof

---

data/thundercore/labels.json

Add label of ThunderCore PoS Staking address

[ThunderCore] Add label of ThunderCore PoS Staking address

---

data/zilliqa/assets/zil1tyc45he8tp96tkyv2372le02tc0hch9p8cxws8/meta.json

[Zilliqa] Update ZilPepe (ZILPEPE)

---

data/thorchain/labels.json

Adds a new address to the thorchain labels

[thorchain] Add Treasury Multisig address

---

data/arweave/labels.json

Proposal to add the Binance account label to ViewBlock.

[ARWEAVE] Add BINANCE label

---

data/zilliqa/assets/zil17slttkmqchmcpev4yps8mguu8rkhv5g4ucu7a6/meta.json

Update Stellar Void (VOID)

---

data/zilliqa/assets/zil1lgj5uykg9lmzjecctjc5fkehdrghd7a9enmwg9/meta.json

- [ x ] Make sure to rebase or clean your history
- [ x ] PR doesn't have any merge conflict
- [ NA ] In case you are migrating a token, delete the old folder in the same PR
Hi @balthazar i set the score to match the readme, please just adjust if not right to the calculation.

[ZILLIQA] Update Kalijo (SEED)
